name: Build charm and publish OCI resources to charmhub staging

on:
  workflow_dispatch:

jobs:
  lib-check:
    name: Check libraries
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Check libs
        uses: canonical/charming-actions/check-libraries@1.0.3
        with:
          credentials: ${{ secrets.CHARMHUB_STAGING_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
  
  tests:
    name: Run Tests
    uses: ./.github/workflows/ci.yaml
  
  publish-indico-image:
    name: Publish indico image to charmhub
    runs-on: ubuntu-latest
    needs: [ lib-check, tests ]
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/publish_oci_resource
        with:
          charm-name: jsimpso-indico-test
          resource-name: jsimpso-indico-image
          charmhub-token: ${{ secrets.CHARMHUB_STAGING_TOKEN }}
  
  publish-indico-nginx-image:
    name: Publish nginx image to charmhub
    runs-on: ubuntu-latest
    needs: [ lib-check, tests ]
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/publish_oci_resource
        with:
          charm-name: jsimpso-indico-test
          resource-name: jsimpso-indico-nginx-image
          charmhub-token: ${{ secrets.CHARMHUB_STAGING_TOKEN }}
